### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by longzw001116** [Enigmatisms/DARTS#1]
Hi, dear author,

Thank you for your awesome work.

Do you have any plans to release the code?

Any response would be greatly appreciated.

**Comment by Enigmatisms** [comment]
Sure, when I am sure that there is no need to work on any patent. Should be able to find out in weeks. You will be the first to be notified, upon code release. Hope this clarifies.

**Comment by Enigmatisms** [comment]
@longzw001116 Yeah. Your code is here!

**Comment by longzw001116** [comment]
> @longzw001116 Yeah. Your code is here!

Nice work！Best of luck snagging Best Paper! ！🎉

**Comment by Enigmatisms** [comment]
Jesus, how can you reply so fast while being in prison?
